pentatrion_vite:
    script_attributes:
        # you can define your attributes that you want to apply
        # for all your script tags

    link_attributes:
        # you can define your attributes that you want to apply
        # for all your link tags

    throw_on_missing_entry: true

    default_build: build1
    builds:
        build1:
            build_directory: build-1
            script_attributes:
                foo: build1
                bar: build1

            link_attributes:
                boo: build1
                bar: build1

        build2:
            build_directory: build-2
            script_attributes:
                foo: build2
                bar: build2
            link_attributes:
                boo: build1
                bar: build1
