services:
    pentatrion_vite.entrypoints_lookup_collection:
        class: Pentatrion\ViteBundle\Asset\EntrypointsLookupCollection

    Pentatrion\ViteBundle\Asset\EntrypointsLookupCollection:
        alias: pentatrion_vite.entrypoints_lookup_collection

    # TODO readd for user customisation
    # pentatrion_vite.entrypoints_lookup:
    #     class: Pentatrion\ViteBundle\Asset\EntrypointsLookup
    #     arguments:
    #         - "%kernel.project_dir%%pentatrion_vite.public_directory%"
    #         - "%pentatrion_vite.default_config%"
    #         - "%pentatrion_vite.configs%"
    #         - "%pentatrion_vite.throw_on_missing_entry%"

    # Pentatrion\ViteBundle\Asset\EntrypointsLookup:
    #     alias: "pentatrion_vite.entrypoints_lookup"

    pentatrion_vite.entrypoint_renderer:
        class: Pentatrion\ViteBundle\Asset\EntrypointRenderer
        arguments:
            - "@pentatrion_vite.entrypoints_lookup_collection"
            - "@pentatrion_vite.tag_renderer_collection"
            - "%pentatrion_vite.absolute_url%"
            - "%pentatrion_vite.preload%"
            - "@?router"
            - "@?event_dispatcher"

    Pentatrion\ViteBundle\Asset\EntrypointRenderer:
        alias: "pentatrion_vite.entrypoint_renderer"

    pentatrion_vite.tag_renderer_collection:
        class: Pentatrion\ViteBundle\Asset\TagRendererCollection

    Pentatrion\ViteBundle\Asset\TagRendererCollection:
        alias: pentatrion_vite.tag_renderer_collection

    # TODO readd for user customisation
    # pentatrion_vite.tag_renderer:
    #     class: Pentatrion\ViteBundle\Asset\TagRenderer
    #     arguments:
    #         - []      # Default script_attributes
    #         - []      # Default link_attributes

    

    pentatrion_vite.twig_entry_files_extension:
        class: Pentatrion\ViteBundle\Twig\EntryFilesTwigExtension
        tags: ["twig.extension"]
        arguments:
            - "@pentatrion_vite.entrypoint_renderer"

    Pentatrion\ViteBundle\Controller\ViteController:
        tags: ["controller.service_arguments"]
        arguments:
            - "%pentatrion_vite.default_config%"
            - "%pentatrion_vite.configs%"
            - "@http_client"
            - "@pentatrion_vite.entrypoints_lookup_collection"
            - "%pentatrion_vite.proxy_origin%"

    Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy:
        arguments:
            - "@pentatrion_vite.file_accessor"
            - "%pentatrion_vite.configs%"
            - "%pentatrion_vite.default_config%"
            - "%pentatrion_vite.absolute_url%"
            - "@?router"
            - true


    pentatrion_vite.preload_assets_event_listener:
        class: Pentatrion\ViteBundle\EventListener\PreloadAssetsEventListener
        tags: ["kernel.event_subscriber"]
        arguments:
            - "@pentatrion_vite.entrypoint_renderer"

    pentatrion_vite.file_accessor:
        class: Pentatrion\ViteBundle\Asset\FileAccessor
        arguments:
            - "%kernel.project_dir%%pentatrion_vite.public_directory%"
            - "%pentatrion_vite.configs%"
            - null

    pentatrion_vite.cache:
        class: Symfony\Component\Cache\Adapter\PhpArrayAdapter
        factory: [Symfony\Component\Cache\Adapter\PhpArrayAdapter, create]
        arguments:
            - '%kernel.cache_dir%/pentatrion_vite.cache.php'
            - '@cache.pentatrion_vite_fallback'

    pentatrion_vite.cache_warmer:
        class:  Pentatrion\ViteBundle\CacheWarmer\EntrypointsCacheWarmer
        tags: ["kernel.cache_warmer"]
        arguments:
            - "%kernel.project_dir%%pentatrion_vite.public_directory%"
            - "%pentatrion_vite.configs%"
            - '%kernel.cache_dir%/pentatrion_vite.cache.php'

    cache.pentatrion_vite_fallback:
        tags: ["cache.pool"]
        parent: cache.system