name: 'vite-plugin-symfony CI'
on:
  push:
    branches: ['main']
  pull_request:

defaults:
  run:
    working-directory: ./src/vite-plugin-symfony

jobs:
  lint:
    name: Eslint and Tsc
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node / Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 'Install JS dependencies'
        run: 'npm ci'

      - name: 'Eslint'
        run: 'npm run lint:check'

      - name: 'Tsc'
        run: 'npm run tsc:check'

      - name: 'Test'
        run: 'npm run test'
